import 'dart:async';

import 'package:flutter/material.dart';

/// Available Yse reaction poses. Asset paths are baked-in text PNGs
/// generated by the content team — do NOT overlay additional text.
enum YseReaction {
  letsGo('assets/images/mascot/yse_lets_go.png'),
  nice('assets/images/mascot/yse_nice.png'),
  hwaiting('assets/images/mascot/yse_hwaiting.png'),
  tryAgain('assets/images/mascot/yse_try_again.png'),
  goodJob('assets/images/mascot/yse_good_job.png'),
  youDidIt('assets/images/mascot/yse_you_did_it.png');

  final String assetPath;
  const YseReaction(this.assetPath);
}

/// Manages the currently-visible reaction pose.
/// Auto-clears after [duration] (default 1.5s). New triggers replace
/// the old one immediately. Silent — no audio.
class YseReactionController extends ChangeNotifier {
  static const Duration defaultDuration = Duration(milliseconds: 1500);

  YseReaction? _current;
  Timer? _timer;

  YseReaction? get current => _current;

  void show(
    YseReaction reaction, {
    Duration duration = defaultDuration,
  }) {
    _current = reaction;
    notifyListeners();

    _timer?.cancel();
    _timer = Timer(duration, () {
      _current = null;
      notifyListeners();
    });
  }

  void clear() {
    _timer?.cancel();
    _current = null;
    notifyListeners();
  }

  @override
  void dispose() {
    _timer?.cancel();
    super.dispose();
  }
}

/// Overlay widget that displays the current reaction pose.
/// Fades in/out over 200ms. Shows idle Yse when no reaction is active.
/// Never blocks gameplay — wrapped in IgnorePointer.
class YseReactionOverlay extends StatelessWidget {
  final YseReactionController controller;
  final double size;

  /// Fallback idle pose shown when no reaction is active.
  final String idleAsset;

  const YseReactionOverlay({
    super.key,
    required this.controller,
    this.size = 180,
    this.idleAsset = 'assets/images/mascot/yse_default.png',
  });

  @override
  Widget build(BuildContext context) {
    return IgnorePointer(
      child: SizedBox(
        width: size,
        height: size,
        child: AnimatedBuilder(
          animation: controller,
          builder: (context, _) {
            final reaction = controller.current;
            final asset = reaction?.assetPath ?? idleAsset;
            final key = reaction?.name ?? 'idle';

            return AnimatedSwitcher(
              duration: const Duration(milliseconds: 200),
              switchInCurve: Curves.easeOut,
              switchOutCurve: Curves.easeIn,
              transitionBuilder: (child, animation) {
                return FadeTransition(opacity: animation, child: child);
              },
              child: Image.asset(
                asset,
                key: ValueKey(key),
                fit: BoxFit.contain,
                errorBuilder: (_, _, _) => const Icon(
                  Icons.auto_stories_rounded,
                  size: 72,
                  color: AppColors.accentTeal,
                ),
              ),
            );
          },
        ),
      ),
    );
  }
}

// Avoids an extra import in callers that only need the overlay.
class AppColors {
  AppColors._();
  static const accentTeal = Color(0xFF2EC4B6);
}